window.scheduleData = {
  upper: {
    Понеділок: [
      {
        time: "8.40-10.15",
        subject: "Алгебра та геометрія",
        type: "pr",
        typeLabel: "Пара",
        teacher: "Довгай",
        link: "https://knu-ua.zoom.us/j/88197737659?pwd=Pg5TzFdemQ94PdCUne7wvtwagVGdeC.1",
        linkText: "Zoom",
      },
      {
        time: "10.35-12.10",
        subject: "Математичний аналіз",
        type: "lek",
        typeLabel: "Пара",
        teacher: "Затула",
        link: "",
        linkText: "-",
      },
      {
        time: "12.20-13.55",
        subject: "Українська та зарубіжна культура",
        type: "lek",
        typeLabel: "Пара",
        teacher: "Сторожук С.В.",
        link: "https://us05web.zoom.us/j/5045167345?pwd=RkFpc3p2TkpmS1BCWW9SMVRBeE1Bdz09&omn=83795793519",
        linkText: "Zoom",
      },
      {
        time: "16:00-17:00",
        subject: "Співбесіда з школою",
        type: "other",
        typeLabel: "Інше",
        teacher: "",
        link: "",
        linkText: "Лінк пізніше",
      },
      {
        time: "17:00-17:30",
        subject: "Пробне заняття з Софійкою",
        type: "ind",
        typeLabel: "Інд",
        teacher: "Мама Елена",
        link: "https://meet.google.com/gzu-qyzi-gzh",
        linkText: "Meet",
      },
      {
        time: "19:00-19:55",
        subject: "Урок з Маринкою",
        type: "ind",
        typeLabel: "Інд",
        teacher: "",
        link: "https://meet.google.com/ubk-ucgw-aun",
        linkText: "Meet",
        description:
          "https://ddashukko.github.io/site/algebra/8/lesson/15-number-sets.html",
      },
      {
        time: "20:00-21:00",
        subject: "Урок з Артуром",
        type: "ind",
        typeLabel: "Інд",
        teacher: "",
        link: "https://us05web.zoom.us/j/85890954549?pwd=7vPzlpqs175m5c7oiDa2JSJX1HtH1j",
        linkText: "Zoom",
        description:
          "https://ddashukko.github.io/site/algebra/9/%D0%9D%D0%B0%D1%81%D1%82%D1%8F/%D1%82%D0%B5%D0%BE%D1%80%D0%B5%D0%BC%D0%B0%D1%81%D0%B8%D0%BD%D1%83%D1%81%D1%96%D0%B2.html +дошка + тест всеосвіта",
      },
    ],
    Вівторок: [
      {
        time: "8.40-10.15",
        subject: "Дискретна математика",
        type: "pr",
        typeLabel: "Пара",
        teacher: "Шевченко",
        link: "https://knu-ua.zoom.us/j/83595388089?pwd=4z0bGaV7blSUHxXvb9AOeKykC09zHS.1",
        linkText: "Zoom",
      },
      {
        time: "10.35-12.10",
        subject: "Програмування",
        type: "pr",
        typeLabel: "Пара",
        teacher: "Карнаух",
        link: "https://meet.google.com/san-qkey-oku",
        linkText: "Meet",
      },
      {
        time: "12.20-13.55",
        subject: "Комп'ютерні мережі",
        type: "pr",
        typeLabel: "Пара",
        teacher: "Зінько",
        link: "https://meet.google.com/cfs-mmog-zuv",
        linkText: "Meet",
      },
      {
        time: "18:00",
        subject: "Урок Настя",
        type: "ind",
        typeLabel: "Інд",
        teacher: "",
        link: "https://meet.google.com/chq-jcpc-htg",
        linkText: "Meet",
      },
    ],
    Середа: [
      {
        time: "8.40-10.15",
        subject: "Алгебра та геометрія",
        type: "pr",
        typeLabel: "Пара",
        teacher: "Давидов",
        link: "https://us04web.zoom.us/j/76479733144?pwd=d0JOQ3ZxL3F6WUhad25xTi9NYmV4Zz09",
        linkText: "Zoom",
      },
      {
        time: "10:00-11:00",
        subject: "Урок Всеволод",
        type: "ind",
        typeLabel: "Інд",
        teacher: "",
        link: "https://meet.google.com/dok-qown-avp",
        linkText: "Meet",
      },
      {
        time: "10.35-12.10",
        subject: "Іноземна мова",
        type: "pr",
        typeLabel: "Пара",
        teacher: "Лисенко",
        link: "",
        linkText: "-",
      },
      {
        time: "12.20-13.55",
        subject: "Дискретна математика",
        type: "pr",
        typeLabel: "Пара",
        teacher: "Єфремов",
        link: "",
        linkText: "-",
      },
      {
        time: "16:00-17:00",
        subject: "Урок Вадим",
        type: "ind",
        typeLabel: "Інд",
        teacher: "",
        link: "https://us05web.zoom.us/j/86860498404?pwd=3z5DCmakQLI4FPkj4kAlDKeIWju4y9.1",
        linkText: "Zoom",
      },
      {
        time: "20:00-21:00",
        subject: "Урок Яра",
        type: "ind",
        typeLabel: "Інд",
        teacher: "",
        link: "https://meet.google.com/yni-xxit-pfc",
        linkText: "Meet",
      },
    ],
    Четвер: [
      {
        time: "8.40-10.15",
        subject: "Комп'ютерні мережі",
        type: "pr",
        typeLabel: "Пара",
        teacher: "Афонін",
        link: "https://knu-ua.zoom.us/j/5124894795?pwd=VjVYNVVISUNiZm40RTdNeHdHSHc4UT09",
        linkText: "Zoom",
      },
      {
        time: "10.35-12.10",
        subject: "Алгебра та геометрія",
        type: "pr",
        typeLabel: "Пара",
        teacher: "Давидов",
        link: "https://us04web.zoom.us/j/76479733144?pwd=d0JOQ3ZxL3F6WUhad25xTi9NYmV4Zz09",
        linkText: "Zoom",
      },
      {
        time: "17:00-17:50",
        subject: "Урок Настя (укрмова)",
        type: "ind",
        typeLabel: "Інд",
        teacher: "",
        link: "https://meet.google.com/iev-xbft-wkn",
        linkText: "Meet",
      },
      {
        time: "18:00-18:50",
        subject: "Урок Настя",
        type: "ind",
        typeLabel: "Інд",
        teacher: "",
        link: "https://meet.google.com/chq-jcpc-htg",
        linkText: "Meet",
      },
      {
        time: "20:00-21:00",
        subject: "Урок Артур",
        type: "ind",
        typeLabel: "Інд",
        teacher: "",
        link: "https://us05web.zoom.us/j/85890954549?pwd=7vPzlpqs175m5c7oiDa2JSJX1HtH1j",
        linkText: "Zoom",
      },
    ],
    "П'ятниця": [
      {
        time: "8.40-10.15",
        subject: "Програмування",
        type: "pr",
        typeLabel: "Пара",
        teacher: "Веклич",
        link: "",
        linkText: "-",
      },
      {
        time: "10:00-11:00",
        subject: "Урок Всеволод",
        type: "ind",
        typeLabel: "Інд",
        teacher: "",
        link: "https://meet.google.com/dok-qown-avp",
        linkText: "Meet",
      },
      {
        time: "10.35-12.10",
        subject: "Математичний аналіз",
        type: "lek",
        typeLabel: "Пара",
        teacher: "Аджубей",
        link: "",
        linkText: "-",
      },
      {
        time: "12.20-13.55",
        subject: "Іноземна мова",
        type: "pr",
        typeLabel: "Пара",
        teacher: "Лисенко",
        link: "",
        linkText: "-",
      },
      {
        time: "14.05-15.40",
        subject: "Українська та зарубіжна культура",
        type: "lek",
        typeLabel: "Пара",
        teacher: "Сторожук",
        link: "https://us05web.zoom.us/j/5045167345?pwd=RkFpc3p2TkpmS1BCWW9SMVRBeE1Bdz09&omn=83795793519",
        linkText: "Zoom",
      },
      {
        time: "16:00-17:00",
        subject: "Урок Вадим",
        type: "ind",
        typeLabel: "Інд",
        teacher: "",
        link: "https://us05web.zoom.us/j/86860498404?pwd=3z5DCmakQLI4FPkj4kAlDKeIWju4y9.1",
        linkText: "Zoom",
      },
    ],
  },
  lower: {
    Понеділок: [
      {
        time: "8.40-10.15",
        subject: "Алгебра та геометрія",
        type: "pr",
        typeLabel: "Пара",
        teacher: "Довгай",
        link: "https://knu-ua.zoom.us/j/88197737659?pwd=Pg5TzFdemQ94PdCUne7wvtwagVGdeC.1",
        linkText: "Zoom",
      },
      {
        time: "10.35-12.10",
        subject: "Математичний аналіз",
        type: "lek",
        typeLabel: "Пара",
        teacher: "Затула",
        link: "",
        linkText: "-",
      },
      {
        time: "12.20-13.55",
        subject: "Українська та зарубіжна культура",
        type: "lek",
        typeLabel: "Пара",
        teacher: "Сторожук С.В.",
        link: "https://us05web.zoom.us/j/5045167345?pwd=RkFpc3p2TkpmS1BCWW9SMVRBeE1Bdz09&omn=83795793519",
        linkText: "Zoom",
      },
      {
        time: "16:00-17:00",
        subject: "Співбесіда з школою",
        type: "other",
        typeLabel: "Інше",
        teacher: "",
        link: "",
        linkText: "Лінк пізніше",
      },
      {
        time: "17:00-17:30",
        subject: "Пробне заняття з Софійкою",
        type: "ind",
        typeLabel: "Інд",
        teacher: "Мама Елена",
        link: "https://meet.google.com/gzu-qyzi-gzh",
        linkText: "Meet",
      },
      {
        time: "19:00-19:55",
        subject: "Урок з Маринкою",
        type: "ind",
        typeLabel: "Інд",
        teacher: "",
        link: "https://meet.google.com/ubk-ucgw-aun",
        linkText: "Meet",
        description:
          "https://ddashukko.github.io/site/algebra/8/lesson/15-number-sets.html",
      },
      {
        time: "20:00-21:00",
        subject: "Урок з Артуром",
        type: "ind",
        typeLabel: "Інд",
        teacher: "",
        link: "https://us05web.zoom.us/j/85890954549?pwd=7vPzlpqs175m5c7oiDa2JSJX1HtH1j",
        linkText: "Zoom",
        description:
          "https://ddashukko.github.io/site/algebra/9/%D0%9D%D0%B0%D1%81%D1%82%D1%8F/%D1%82%D0%B5%D0%BE%D1%80%D0%B5%D0%BC%D0%B0%D1%81%D0%B8%D0%BD%D1%83%D1%81%D1%96%D0%B2.html +дошка + тест всеосвіта",
      },
    ],
    Вівторок: [
      {
        time: "8.40-10.15",
        subject: "Дискретна математика",
        type: "pr",
        typeLabel: "Пара",
        teacher: "Шевченко",
        link: "https://knu-ua.zoom.us/j/83595388089?pwd=4z0bGaV7blSUHxXvb9AOeKykC09zHS.1",
        linkText: "Zoom",
      },
      {
        time: "10.35-12.10",
        subject: "Програмування",
        type: "pr",
        typeLabel: "Пара",
        teacher: "Карнаух",
        link: "https://meet.google.com/san-qkey-oku",
        linkText: "Meet",
      },
      {
        time: "12.20-13.55",
        subject: "Комп'ютерні мережі",
        type: "pr",
        typeLabel: "Пара",
        teacher: "Зінько",
        link: "https://meet.google.com/cfs-mmog-zuv",
        linkText: "Meet",
      },
      {
        time: "18:00",
        subject: "Урок Настя",
        type: "ind",
        typeLabel: "Інд",
        teacher: "",
        link: "https://meet.google.com/chq-jcpc-htg",
        linkText: "Meet",
      },
    ],
    Середа: [
      {
        time: "8.40-10.15",
        subject: "Алгебра та геометрія",
        type: "pr",
        typeLabel: "Пара",
        teacher: "Давидов",
        link: "https://us04web.zoom.us/j/76479733144?pwd=d0JOQ3ZxL3F6WUhad25xTi9NYmV4Zz09",
        linkText: "Zoom",
      },
      {
        time: "10:00-11:00",
        subject: "Урок Всеволод",
        type: "ind",
        typeLabel: "Інд",
        teacher: "",
        link: "https://meet.google.com/dok-qown-avp",
        linkText: "Meet",
      },
      {
        time: "10.35-12.10",
        subject: "Іноземна мова",
        type: "pr",
        typeLabel: "Пара",
        teacher: "Лисенко",
        link: "",
        linkText: "-",
      },
      {
        time: "12.20-13.55",
        subject: "Дискретна математика",
        type: "pr",
        typeLabel: "Пара",
        teacher: "Єфремов",
        link: "",
        linkText: "-",
      },
      {
        time: "16:00-17:00",
        subject: "Урок Вадим",
        type: "ind",
        typeLabel: "Інд",
        teacher: "",
        link: "https://us05web.zoom.us/j/86860498404?pwd=3z5DCmakQLI4FPkj4kAlDKeIWju4y9.1",
        linkText: "Zoom",
      },
      {
        time: "20:00-21:00",
        subject: "Урок Яра",
        type: "ind",
        typeLabel: "Інд",
        teacher: "",
        link: "https://meet.google.com/yni-xxit-pfc",
        linkText: "Meet",
      },
    ],
    Четвер: [
      {
        time: "8.40-10.15",
        subject: "Комп'ютерні мережі",
        type: "pr",
        typeLabel: "Пара",
        teacher: "Афонін",
        link: "https://knu-ua.zoom.us/j/5124894795?pwd=VjVYNVVISUNiZm40RTdNeHdHSHc4UT09",
        linkText: "Zoom",
      },
      {
        time: "10.35-12.10",
        subject: "Алгебра та геометрія",
        type: "pr",
        typeLabel: "Пара",
        teacher: "Давидов",
        link: "https://us04web.zoom.us/j/76479733144?pwd=d0JOQ3ZxL3F6WUhad25xTi9NYmV4Zz09",
        linkText: "Zoom",
      },
      {
        time: "17:00-17:50",
        subject: "Урок Настя (укрмова)",
        type: "ind",
        typeLabel: "Інд",
        teacher: "",
        link: "https://meet.google.com/iev-xbft-wkn",
        linkText: "Meet",
      },
      {
        time: "18:00-18:50",
        subject: "Урок Настя",
        type: "ind",
        typeLabel: "Інд",
        teacher: "",
        link: "https://meet.google.com/chq-jcpc-htg",
        linkText: "Meet",
      },
      {
        time: "20:00-21:00",
        subject: "Урок Артур",
        type: "ind",
        typeLabel: "Інд",
        teacher: "",
        link: "https://us05web.zoom.us/j/85890954549?pwd=7vPzlpqs175m5c7oiDa2JSJX1HtH1j",
        linkText: "Zoom",
      },
    ],
    "П'ятниця": [
      {
        time: "8.40-10.15",
        subject: "Програмування",
        type: "pr",
        typeLabel: "Пара",
        teacher: "Веклич",
        link: "",
        linkText: "-",
      },
      {
        time: "10:00-11:00",
        subject: "Урок Всеволод",
        type: "ind",
        typeLabel: "Інд",
        teacher: "",
        link: "https://meet.google.com/dok-qown-avp",
        linkText: "Meet",
      },
      {
        time: "10.35-12.10",
        subject: "Математичний аналіз",
        type: "lek",
        typeLabel: "Пара",
        teacher: "Аджубей",
        link: "",
        linkText: "-",
      },
      {
        time: "12.20-13.55",
        subject: "Іноземна мова",
        type: "pr",
        typeLabel: "Пара",
        teacher: "Лисенко",
        link: "",
        linkText: "-",
      },
      {
        time: "14.05-15.40",
        subject: "Українська та зарубіжна культура",
        type: "lek",
        typeLabel: "Пара",
        teacher: "Сторожук",
        link: "https://us05web.zoom.us/j/5045167345?pwd=RkFpc3p2TkpmS1BCWW9SMVRBeE1Bdz09&omn=83795793519",
        linkText: "Zoom",
      },
      {
        time: "16:00-17:00",
        subject: "Урок Вадим",
        type: "ind",
        typeLabel: "Інд",
        teacher: "",
        link: "https://us05web.zoom.us/j/86860498404?pwd=3z5DCmakQLI4FPkj4kAlDKeIWju4y9.1",
        linkText: "Zoom",
      },
    ],
  },
};
